### ISSUE TITLE
Issues about the 'FEC_matrices'

### ISSUE THREAD

**Issue by YingyWang** [borgr/GEC_UD_divergences#1]
Hi, Leshem Choshen!
I had tried run the .py file [GEC_UD_divergences_m2.py](https://github.com/borgr/GEC_UD_divergences/tree/master/using_m2) with the fce data files under [data/UD_English-ESL/data/](https://github.com/borgr/GEC_UD_divergences/tree/master/data/UD_English-ESL/data). But I couldn't get the same pos matrix and path matrix as you gave under [confusion_matrices/FEC_matrices/](https://github.com/borgr/GEC_UD_divergences/tree/master/confusion_matrices/FEC_matrices). Did you do ever modify the  [GEC_UD_divergences_m2.py](https://github.com/borgr/GEC_UD_divergences/tree/master/using_m2)  or the data files? 
Looking forwards to your reply!

**Comment by borgr** [comment]
Hey, How different were they? If they are similar but not exactly the same,
then it might be that some small things changed (maybe the UD
parser/version?)



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
03/12/20
09:36:46 a. m.

**Comment by YingyWang** [comment]
Thanks for your reply!
They look similar but not exactly the same in numbers.
But I didn't parse txt files using UDpipe, I just run the code with the conllu files under data/UD_English-ESL/data/. Was it the same files you used to get the matrices under  confusion_matrices/FEC_matrices/ ?

**Comment by borgr** [comment]
Ok, I see, if they are quite similar, then I wouldn't worry too much, it
might be that some minor changes when done when making the code ready to be
public.
BTW, I am not sure what your use is, but maybe this implementation may also
be of use to you.
https://github.com/matanel-oren/serrant

**Comment by YingyWang** [comment]
Thanks a lot~ I'll try later🌞🌞🌞

**Comment by YingyWang** [comment]
Sorry to bother you again, I have tried serrant and got the same matrices as previous……Obvevious, the problem is not about errant,   maybe the fce conllu files I used (under 'data/UD_English-ESL/data/') is not the extract ones you used to get the matrices under 'confusion_matrices/FEC_matrices/'. So could you please offer me the conllu files and m2 files you used? 
Attached is the pos matrix file I got.
[en_esl-ud-train.conllu_pos_matrix.csv.txt](https://github.com/borgr/GEC_UD_divergences/files/5641274/en_esl-ud-train.conllu_pos_matrix.csv.txt)

**Comment by borgr** [comment]
From manually inspecting them the results indeed don't look the same but
are similar. I compared the total number and I see you got more sentences.
So this does seem likely to be a bug we fixed avoiding skipping some
sentences.
Is the small difference between the matrices significant to your work in
any way?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
06/12/20
08:52:30 a. m.

**Comment by YingyWang** [comment]
Hi~ Thanks for your relpy~
Did u mean there is a bug in file 'GEC_UD_Divergence_m2.py' that can causeskipping some sentence? If so, then could you please update the file? I really appreciate your work, and I am  gonna conduct the similar experiments in the other  language. But I‘m afraid I won't get the correct scientific matrices. So I tested the code file using your data, but got different matrices.

**Comment by borgr** [comment]
I meant a minor bug was fixed before publishing the code, but I can
replicate it tomorrow and tell you what I get.  Anyway, the matrix you
uploaded seems reasonable, so I think you are doing fine.

**Comment by borgr** [comment]
I tried it a bit, regarding creating the matrices there, it was done with an earlier code, so it is quite possible it was not done with the same conllu files. I attach here conllu files and m2 and results, git pull the code for any changes and run it on the files. Tell me if you get the same results as in the zip file.

[example.zip](https://github.com/borgr/GEC_UD_divergences/files/5658288/example.zip)

**Comment by YingyWang** [comment]
Thanks for all that you did~ I'll try right away.

**Comment by YingyWang** [comment]
Hi~
I tried the files, and I got the same pos matrix as  in the zip file.  So the results in your paper was not obtained by the code released in this respository ?

I also found the conllu files in the zip file is exactly the same as you gived in the folder [GEC_UD_divergences/data/UD_English-ESL/data/](https://github.com/borgr/GEC_UD_divergences/tree/master/data/UD_English-ESL/data). 
And the reason why I got different pos matrix from the one in the zip file is that I used the different m2 file (atteached ). I got this m2 file using txt files extracted from conllu files, not 'en_esl-ud-train.conllu.src' and 'en_esl-ud-train.conllu.ref' got by running 'align.py'. Because there was some puncts and words missed when you run the 'align.py'. For example , an word 'taken' was missed in the sentence whose sent_id is '0102_2000_12-doc724.xml-11', so the correction was changed from replacing 'taken' to adding 'take'. 
[en_esl-ud-train.m2.zip](https://github.com/borgr/GEC_UD_divergences/files/5663976/en_esl-ud-train.m2.zip)

**Comment by borgr** [comment]
The matrices were taken with an earlier version of the code so some things
might have changed since (probably things related to preprocessing, like
the m2 differences you see here. Also ERRANT itself changed a version, not
sure if it affected anything) The bottom line is that you seem to run it
alright.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/12/20
08:51:56 a. m.

**Comment by YingyWang** [comment]
Thank you for your patient reply~
